<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="chassis_length" value="0.360"/>
    <xacro:property name="chassis_width" value="0.200"/>
    <xacro:property name="chassis_height" value="0.100"/>
    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="wheel_radius" value="0.0675"/>
    <xacro:property name="wheel_thickness" value="0.043"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.226"/>
    <xacro:property name="wheel_offset_y" value="0.1485"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>
    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <!-- Base Link -->
    <link name="base_link"/>

    <!-- Chassis -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>
    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
    </link>

    <!-- Wheels -->
    <xacro:macro name="wheel" params="name parent x y z rpy axis">
        <joint name="${name}_joint" type="continuous">
            <parent link="${parent}"/>
            <child link="${name}"/>
            <origin xyz="${x} ${y} ${z}" rpy="${rpy}"/>
            <axis xyz="${axis}"/>
        </joint>
        <link name="${name}">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
            </collision>
        </link>
    </xacro:macro>

    <xacro:wheel name="left_back_wheel" parent="base_link" x="0" y="${wheel_offset_y}" z="0" rpy="-${pi/2} 0 0" axis="0 0 1"/>
    <xacro:wheel name="left_front_wheel" parent="base_link" x="${wheel_offset_x}" y="${wheel_offset_y}" z="0" rpy="-${pi/2} 0 0" axis="0 0 1"/>
    <xacro:wheel name="right_back_wheel" parent="base_link" x="0" y="${-wheel_offset_y}" z="0" rpy="${pi/2} 0 0" axis="0 0 -1"/>
    <xacro:wheel name="right_front_wheel" parent="base_link" x="${wheel_offset_x}" y="${-wheel_offset_y}" z="0" rpy="${pi/2} 0 0" axis="0 0 -1"/>

</robot>
